config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets do
    resources :comments
    resources :likes
  end
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :user, presence: true
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  mount_uploader :img, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImageUploader
  validates :profile, length: { maximum: 200 }
  has_many :tweets
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "dhh",password: "secret",only: :destroy
    def create
        @tweet = Tweet.find(params[:tweet_id])
        @comment = @tweet.comments.create(comment_params)
        redirect_to tweet_path(@tweet)
    end

    def destroy
        @tweet = Tweet.find(params[:tweet_id])
        @comment = @tweet.comments.find(params[:id])
        @comment.destroy
        redirect_to tweet_path(@tweet)
    end

    private
     def comment_params
        params.require(:comment).permit(:commenter, :body)
     end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.create(tweet_id: params[:tweet_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create]
  def index
      @tweets = Tweet.all
  end

  def show
      @tweet = Tweet.find(params[:id])
      @like = Like.new
  end

  def new
      @tweet = Tweet.new
  end

  def edit
      @tweet = Tweet.find(params[:id])
  end

  def create
      @tweet = Tweet.new(tweet_params)
      @tweet.user_id = current_user.id

      if @tweet.save
          redirect_to @tweet
      else
          render 'new'
      end
  end

  def update
      @tweet = Tweet.find(params[:id])

      if @tweet.update(tweet_params)
          redirect_to @tweet
      else
          render 'edit'
      end
  end

  def destroy
      @tweet = Tweet.find(params[:id])
      @tweet.destroy

      redirect_to tweets_path
  end

  def ensure_correct_user
      @post = Post.find_by(id:params[:id])
      if @post.user_id != @current_user.id
        flash[:notice] = "権限がありません"
        redirect_to tweets_path
    end
  end

  private
      def tweet_params
          params.require(:tweet).permit(:title, :text, :img, :remove_img, :user_id)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
        if @isRoom
        else
          @room = Room.new
          @entry = Entry.new
        end
      end
    end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
    end
end

app/views/comments/_comment.html.erb
<p>
 <strong>Commenter</strong>
 <%= comment.commenter %>
</p>

<p>
 <strong>Comment</strong>
 <%= comment.body %>
</p>

<p>
 <%= link_to 'Destroy Comment', [comment.tweet, comment],method: :delete, data:{confirm: 'Are you sure?' }%>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @tweet, @tweet.comments.build ], local: true) do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/rooms/show.html.erb
<h1>DM</h1>

<h4>参加者</h4>
<% @entries.each do |e| %>
  <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.email%>さん</a></strong></h5>
<% end %>

<hr>
<% if @messages.present? %>
  <% @messages.each do |m| %>
    <strong><%= m.content %></strong>
    <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.email %>さん</a></strong></small>
    <hr>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>

<%= form_for @message do |f| %>
  <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <br>
  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>

app/views/tweets/_form.html.erb
<%= form_with scope: :tweet, url: tweets_path, local: true do |form| %>
  <% if @tweet.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited
      this tweet from being saved:</h2>
    <ul>
    <% @tweet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>


  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.label :images %><br />
    <%= form.file_field :img %>
  </p>

  <p><%= form.check_box :remove_img %>画像を削除する</p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>
<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Tweets#index</h1>
<p>Find me in app/views/tweets/index.html.erb</p>
<h1>Listing tweets</h1>
<%= link_to 'New tweet', new_tweet_path %>
<table>
 <tr>
  <th>Title</th>
  <th>Text</th>
  <th colspan="3"></th>
 </tr>
<% @tweets.each do |tweet| %>
    <tr>
     <td><%= tweet.title %></td>
     <td><%= tweet.text %></td>
     <td><%= link_to 'Show',tweet_path(tweet) %></td>
     <td><%= link_to 'Edit',edit_tweet_path(tweet) %></td>
     <td><%= link_to 'Destroy',tweet_path(tweet),method: :delete, data: {confirm: 'Are you sure?'} %></td>
     <td>(<%= tweet.liked_users.count %>)</td>
    </tr>
<% end %>
</table>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>
<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>
<p>
 <%= @tweet.user.username %>
</p>

<p>
 <strong>Title:</strong>
 <%= @tweet.title %>
</p>

<p>
 <strong>Text:</strong>
 <%= @tweet.text %>
</p>

<p>
  <strong>Image:</strong><br>
  <img src="<%= @tweet.img %>" width="500px" height="500px" />
</p>

<h3>いいね件数: <%= @tweet.likes.count %></h3>
<% if current_user.already_liked?(@tweet) %>
  <%= button_to 'いいねを取り消す', tweet_like_path(@tweet), method: :delete %>
<% else %>
  <%= button_to 'いいね', tweet_likes_path(@tweet) %>
<% end %>
<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <ul>
   <li><%= user.username %></li>
  </ul>
<% end %>

<h2>Comments</h2>
<%= render @tweet.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Back', tweets_path %> | <%= link_to 'Edit', edit_tweet_path(@tweet) %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |form| %>
    <div><%= form.hidden_field :following_id %></div>
    <%= form.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
  <% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
<% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
<% else %>
  <%= render 'follow' %>
<% end %>
</div>
<% end %> 

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |form| %>
    <%= form.submit "Unfollow", class: "btn btn-large follow-btn" %>
  <% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
  <a href="/users/<%= user.id %>"><%= user.email %></a>
  <hr>
<% end %>

app/views/users/show.html.erb
<p>Profile</p>
ユーザー名:<%= @user.username %>さん<br>
メールアドレス:<%= @user.email %><br>
プロフィール:<%= @user.profile %><br>
<img src="<%= @user.image %>" width="200px" height="200px" style="border-radius:50%;object-fit:cover;"><br>
<%= render 'follow_form' %>
<%= render 'stats' %>
<h2>投稿内容</h2>
<% @user.tweets.each do |tweet| %>
  <a href="/tweets/<%= tweet.id %>"><%= tweet.text %></a>
  <hr>
<% end %>
<h3>いいねしている投稿</h3>
<% @user.liked_tweets.each do |tweet| %>
  <%= tweet.user.email %>
  <%= tweet.text %>
<% end %>

<%= link_to 'UserArchive', users_path %>
<% if @user.id == current_user.id %>

<% else %>
  <% if @isRoom == true %>
    <p><a href="/rooms/<%= @roomId %>">チャットへ</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <%= f.submit "チャットを始める" %>
    <% end %>
  <% end %>
<% end %>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
    <table>
    <tr>
      <td><%= user.username %> </td>
      <td><%= link_to '詳細', user_path(user) %></td>
    </tr>
    
    </table>
    <% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
    <table>
    <tr>
      <td><%= user.username %> </td>
      <td><%= link_to '詳細', user_path(user) %></td>
    </tr>
    
    </table>
    <% end %>